kind: PersistentVolume
apiVersion: v1
metadata:
  name: lugati-front-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/lugati-pv/front
