kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lugati-static-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: lugati-static-pv
