kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lugati-socket-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi
  volumeName: lugati-socket-pv
