kind: Service
apiVersion: v1
metadata:
  name: lugati-backend-service
spec:
  selector:
    app: lugati-backend-container
  ports:
  - name: view
    protocol: TCP
    port: 80
    targetPort: 80
  - name: sync
    protocol: TCP
    port: 22
    nodePort: 30002
    targetPort: 22
  type: NodePort
